package nerrad.ui;

import java.io.IOException;
import java.util.Collections;

import javafx.beans.binding.Bindings;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.control.Label;
import javafx.scene.layout.HBox;

/**
 * Represents one chat message with a speaker avatar and a text bubble.
 */
public class DialogBox extends HBox {
    private static final String ERROR_PREFIX = "  OOPS!!!";
    private static final double MINIMUM_BUBBLE_WIDTH = 180.0;
    private static final double BUBBLE_WIDTH_OFFSET = 80.0;

    @FXML
    private Label dialog;

    @FXML
    private Label avatar;

    private DialogBox(String text, String avatarText) {
        try {
            FXMLLoader fxmlLoader = new FXMLLoader(DialogBox.class.getResource("/view/DialogBox.fxml"));
            fxmlLoader.setController(this);
            fxmlLoader.setRoot(this);
            fxmlLoader.load();
        } catch (IOException exception) {
            throw new IllegalStateException("Unable to load a chat message.", exception);
        }

        getStylesheets().add(DialogBox.class.getResource("/css/dialog-box.css").toExternalForm());
        dialog.setText(text);
        avatar.setText(avatarText);
        dialog.maxWidthProperty().bind(
                Bindings.max(widthProperty().subtract(BUBBLE_WIDTH_OFFSET), MINIMUM_BUBBLE_WIDTH));
    }

    /**
     * Flips a dialog so that a chatbot reply appears on the left.
     */
    private void flip() {
        ObservableList<Node> children = FXCollections.observableArrayList(getChildren());
        Collections.reverse(children);
        getChildren().setAll(children);
        setAlignment(Pos.TOP_LEFT);
        dialog.getStyleClass().add("reply-label");
    }

    /**
     * Creates a right-aligned dialog for a user's command.
     *
     * @param text Command entered by the user.
     * @return User dialog.
     */
    public static DialogBox getUserDialog(String text) {
        return new DialogBox(text, "You");
    }

    /**
     * Creates a left-aligned dialog for Nerrad's response.
     *
     * @param text Response generated by Nerrad.
     * @return Nerrad dialog.
     */
    public static DialogBox getNerradDialog(String text) {
        DialogBox dialogBox = new DialogBox(text, "N");
        dialogBox.flip();
        if (text.startsWith(ERROR_PREFIX)) {
            dialogBox.dialog.getStyleClass().add("error-label");
            dialogBox.avatar.getStyleClass().add("error-avatar");
        }
        return dialogBox;
    }
}
